In [76]:
# default import, might be useless

# deep learning library
import torch
import torchvision
from   torch.utils.data import DataLoader
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

# to import data
import torchvision.transforms as transforms 
import torchvision.datasets.mnist as mnist  

# we use torch.cuda.Event(enable_timing=True) to measure time
# if you don't have cuda, you can use instead :
# from timeit import default_timer as timer
# import time

import collections           # for ordered_dictionnary
import torch.nn.init as init # to initialize model

import copy # for copy.deepcopy( ... )

import numpy as np

# to make and display plots
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure 

# to format time to strings
import datetime                      

import math # for ceil ()

import IPython.display # to display .png

import time
import collections
import os
import sys
import torch
import torch.nn
from torch.autograd import Variable
import torch.nn as nn

from torch.distributions.normal import Normal

In [53]:
c = torch.linspace(0, 1, steps=11)
c = torch.transpose(c.repeat(100,1),0,-1)
print(c.shape)

torch.Size([11, 100])


In [60]:
a = 5
b = 15
c = torch.linspace(0, 1, steps=11)
c = torch.transpose(c.repeat(1,3,32,32,1),0,-1).squeeze(-1)

In [61]:
print(c.shape)
print(c[0,:,:,:])
print(c[:,0,0,0])

torch.Size([11, 3, 32, 32])
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [21]:
d = c*b+(1-c)*a

In [22]:
print(d[:,0,0])

tensor([5., 5.])


In [65]:
g = torch.ones(5,5,5)
print( g[0].shape )

torch.Size([5, 5])


In [68]:
a = torch.randn(2,2)
b = torch.zeros(2,2)
c = torch.max(a,b)

print(a)
print(b)
print(c)

tensor([[-0.5791,  0.4211],
        [-0.6233,  0.7187]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0000, 0.4211],
        [0.0000, 0.7187]])


In [70]:
a = torch.randn(2,2)
b = a.exp()
print(b)

tensor([[2.7998, 0.2312],
        [2.8171, 0.2961]])


In [74]:
z = torch.tensor([100,10,1],dtype=torch.float)
print( z.log() )

tensor([4.6052, 2.3026, 0.0000])


In [85]:
mu  = torch.tensor([0,10],dtype=torch.float)
std = torch.tensor([1,5],dtype=torch.float)
nor = Normal(mu, std)
z   = nor.sample([4,3])
print(z.shape)
print(z)

torch.Size([4, 3, 2])
tensor([[[-0.1356,  9.7653],
         [ 0.9093,  8.7009],
         [-0.6182,  5.6125]],

        [[-0.6682, 20.8971],
         [ 0.1254,  9.8716],
         [-0.5835, 10.3099]],

        [[-1.1301,  5.5801],
         [ 0.8912,  9.4614],
         [-0.0744, 10.2040]],

        [[-1.1459, 17.3478],
         [-1.3308, 10.0377],
         [-0.3686,  9.8107]]])


In [87]:
m,_ = z.max(-1)
print(m.shape)
print(m)

torch.Size([4, 3])
tensor([[ 9.7653,  8.7009,  5.6125],
        [20.8971,  9.8716, 10.3099],
        [ 5.5801,  9.4614, 10.2040],
        [17.3478, 10.0377,  9.8107]])


In [100]:
m = torch.linspace(1, 10, steps=10)
print(m)
m = m.view(5,2).contiguous()
print(m)
m = m.unsqueeze(1).repeat(1,3,1).contiguous()
print(m)
m = m.view(15,2).contiguous()
print(m)
m = m.view(5,3,2).contiguous()
print(m)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
tensor([[[ 1.,  2.],
         [ 1.,  2.],
         [ 1.,  2.]],

        [[ 3.,  4.],
         [ 3.,  4.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 5.,  6.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 7.,  8.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [ 9., 10.],
         [ 9., 10.]]])
tensor([[ 1.,  2.],
        [ 1.,  2.],
        [ 1.,  2.],
        [ 3.,  4.],
        [ 3.,  4.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 5.,  6.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 7.,  8.],
        [ 7.,  8.],
        [ 9., 10.],
        [ 9., 10.],
        [ 9., 10.]])
tensor([[[ 1.,  2.],
         [ 1.,  2.],
         [ 1.,  2.]],

        [[ 3.,  4.],
         [ 3.,  4.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 5.,  6.],
         [ 5.,  6.]],

        [[ 7.,  8.]

In [ ]:
m = torch.linspace(1, 10, steps=10)
m = m.view(5,2).contiguous() # (bs,dimz)
m = m.unsqueeze(1).repeat(1,3,1).contiguous() # (bs,K,dimz)
m = m.view(15,2).contiguous() # (bs * K,dimz)
m = m.view(5,3,2).contiguous() # (bs,K,dimz)

In [104]:
K = 20
Kt = torch.tensor(K,dtype=torch.float)
print(Kt.shape)

torch.Size([])


In [105]:
u = torch.ones(512)
print(u.shape)
print(u.unsqueeze(1).shape)

torch.Size([512])
torch.Size([512, 1])


In [106]:
u = np.ones([512])
print( u.shape )

(512,)


In [108]:
malist  = [1]
malist += [2]
malist += [5]
arr = np.asarray(malist)
print(malist)
print(arr)

[1, 2, 5]
[1 2 5]
