In [2]:
# default import, might be useless

# deep learning library
import torch
import torchvision
from   torch.utils.data import DataLoader
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

# to import data
import torchvision.transforms as transforms 
import torchvision.datasets.mnist as mnist  

# we use torch.cuda.Event(enable_timing=True) to measure time
# if you don't have cuda, you can use instead :
# from timeit import default_timer as timer
# import time

import collections           # for ordered_dictionnary
import torch.nn.init as init # to initialize model

import copy # for copy.deepcopy( ... )

import numpy as np

# to make and display plots
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure 

# to format time to strings
import datetime                      

import math # for ceil ()

import IPython.display # to display .png

import time
import collections
import os
import sys
import torch
import torch.nn
from torch.autograd import Variable
import torch.nn as nn

In [53]:
c = torch.linspace(0, 1, steps=11)
c = torch.transpose(c.repeat(100,1),0,-1)
print(c.shape)

torch.Size([11, 100])


In [60]:
a = 5
b = 15
c = torch.linspace(0, 1, steps=11)
c = torch.transpose(c.repeat(1,3,32,32,1),0,-1).squeeze(-1)

In [61]:
print(c.shape)
print(c[0,:,:,:])
print(c[:,0,0,0])

torch.Size([11, 3, 32, 32])
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [21]:
d = c*b+(1-c)*a

In [22]:
print(d[:,0,0])

tensor([5., 5.])


In [65]:
g = torch.ones(5,5,5)
print( g[0].shape )

torch.Size([5, 5])


In [68]:
a = torch.randn(2,2)
b = torch.zeros(2,2)
c = torch.max(a,b)

print(a)
print(b)
print(c)

tensor([[-0.5791,  0.4211],
        [-0.6233,  0.7187]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0000, 0.4211],
        [0.0000, 0.7187]])


In [70]:
a = torch.randn(2,2)
b = a.exp()
print(b)

tensor([[2.7998, 0.2312],
        [2.8171, 0.2961]])
